"""## CORRECT bpy API CHEAT-SHEET section."""

import bpy


def section_recipe():
    """Canonical, correct bpy API so the AI does not hallucinate methods."""
    return [
        "## CORRECT bpy API CHEAT-SHEET (follow these patterns EXACTLY)",
        "Use ONLY the APIs shown here. Do NOT invent methods. Common hallucinations to AVOID:",
        "  - `bpy.types.Bone.Matrix()`            <-- DOES NOT EXIST",
        "  - `bone.rotate(...)` / `pose_bone.rotate(...)`  <-- DOES NOT EXIST",
        "  - importing Matrix/Euler/Quaternion from `bpy` <-- they live in `mathutils`",
        "  - `Quaternion((axis, angle))` / `Quaternion((Vector((1,0,0)), angle))`"
        "  <-- WRONG: that is ONE argument of length 2 and raises"
        " 'sequence length is 2, expected [3 - 4]'. The axis-angle form takes TWO"
        " SEPARATE arguments: `Quaternion(axis, angle)` (axis is the 3-sequence,"
        " angle is the radians float).",
        f"  - `action.fcurves` <-- DOES NOT EXIST in Blender {bpy.app.version_string}"
        " (layered actions). See the fcurve-iteration helper below.",
        "",
        "Iterating an action's F-Curves (Blender 4.4+/5.x layered actions):",
        "    # `action.fcurves` was removed; fcurves now live under slots/layers/strips.",
        "    def iter_fcurves(action):",
        "        if hasattr(action, 'fcurves') and not getattr(action, 'is_action_layered', False):",
        "            yield from action.fcurves            # legacy files",
        "            return",
        "        for layer in action.layers:",
        "            for strip in layer.strips:",
        "                for slot in action.slots:",
        "                    cb = strip.channelbag(slot)",
        "                    if cb:",
        "                        yield from cb.fcurves",
        "    # usage: for fc in iter_fcurves(arm.animation_data.action): fc.keyframe_points...",
        "    # set interpolation example:",
        "    #   for fc in iter_fcurves(act):",
        "    #       for kp in fc.keyframe_points: kp.interpolation = 'BEZIER'",
        "- The active action is `arm.animation_data.action` (may be None until you insert a key).",
        "",
        "Correct imports:",
        "    import bpy, math",
        "    from mathutils import Euler, Quaternion, Vector, Matrix",
        "",
        "Get the armature + enter pose mode:",
        "    arm = next(o for o in bpy.data.objects if o.type == 'ARMATURE')",
        "    bpy.context.view_layer.objects.active = arm",
        "    bpy.ops.object.mode_set(mode='POSE')",
        "",
        "Rotate a pose bone in its LOCAL space and keyframe it (Euler example):",
        "    pb = arm.pose.bones['mixamorig:RightArm']",
        "    pb.rotation_mode = 'XYZ'                 # so rotation_euler is used",
        "    pb.rotation_euler = Euler((math.radians(30), 0.0, 0.0), 'XYZ')",
        "    pb.keyframe_insert(data_path='rotation_euler', frame=10)",
        "",
        "Quaternion example (when rotation_mode == 'QUATERNION', the default here):",
        "    # axis-angle: TWO separate args (axis 3-seq, angle radians). NOT one tuple.",
        "    pb.rotation_quaternion = Quaternion((1, 0, 0), math.radians(30))  # axis, angle",
        "    pb.rotation_quaternion = Quaternion(Vector((1, 0, 0)), math.radians(30))  # same, Vector axis",
        "    # raw [w, x, y, z] components form takes ONE 4-sequence: Quaternion((1, 0, 0, 0))",
        "    pb.keyframe_insert(data_path='rotation_quaternion', frame=10)",
        "",
        "Translate / scale a pose bone (local space) and keyframe:",
        "    pb.location = Vector((0.0, 0.1, 0.0))   # along bone-local axes",
        "    pb.keyframe_insert(data_path='location', frame=10)",
        "    pb.scale = Vector((1, 1, 1)); pb.keyframe_insert(data_path='scale', frame=10)",
        "",
        "Export the animated scene, OVERWRITING the original file (do this LAST, headless).",
        "Use the exporter that matches the file's extension; frame_start/end/fps must be set first:",
        "    bpy.ops.object.mode_set(mode='OBJECT')   # leave POSE mode before exporting",
        "    # glTF (.glb / .gltf) — best for web preview (three.js / <model-viewer>):",
        "    bpy.ops.export_scene.gltf(",
        "        filepath='/abs/path/model.glb',",
        "        export_format='GLB',          # 'GLB' for .glb, 'GLTF_SEPARATE' for .gltf",
        "        export_animations=True,       # bake the keyframed action into the file",
        "        export_yup=True,              # glTF/three.js/web is Y-up",
        "    )",
        "    # FBX (.fbx) — when overwriting an .fbx upload:",
        "    bpy.ops.export_scene.fbx(",
        "        filepath='/abs/path/model.fbx',",
        "        bake_anim=True,               # write the keyframed action into the FBX",
        "        add_leaf_bones=False,",
        "    )",
        "    # Notes: pass the FULL output path you were given (same path you imported from).",
        "    # Do NOT call render or open a window; the exporter writes the file directly.",
        "    # No quit/GUI call is needed — the script runs top-to-bottom and returns.",
        "",
        "Notes:",
        "- pose-bone rotations/locations are in the bone's LOCAL space (the local axes listed",
        "  above), composed on top of the rest pose — identity basis means 'rest pose'.",
        "- NEVER edit the rest pose. Stay in POSE mode (matrix_basis only); do NOT enter EDIT mode",
        "  to change edit_bone head/tail/roll, and do NOT call `bpy.ops.pose.armature_apply()`.",
        "  Posing a bone WITHOUT keyframing it leaks into the exported bind pose — always keyframe.",
        "- A pose bone uses EITHER rotation_euler OR rotation_quaternion depending on",
        "  rotation_mode. Set rotation_mode first, then key the matching data_path.",
        "- To reset a bone to rest at a frame: set its rotation to identity",
        "  (Euler((0,0,0)) or Quaternion((1,0,0,0))) and keyframe it.",
        "- bpy.ops.* operators need POSE or OBJECT mode set appropriately; keyframe_insert on the",
        "  pose bone does NOT require an operator.",
        "- If you must build a matrix, use mathutils: `Matrix.Rotation(angle, 4, 'X')`,",
        "  `Matrix.Translation(v)`, `Matrix.Identity(4)`. There is no `bpy.types.Bone.Matrix`.",
        "",
    ]
